<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <NoWarn>$(NoWarn);NU1903</NoWarn>
    <AssemblyName>Admins.Bans</AssemblyName>
    <OutputPath>$(MSBuildThisFileDirectory)build/</OutputPath>
    <PublishDir>$(OutputPath)publish/Admins.Bans</PublishDir>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Dommel" Version="3.4.0" />
    <PackageReference Include="FluentMigrator" Version="7.1.0" />
    <PackageReference Include="FluentMigrator.Runner" Version="7.1.0" />
    <PackageReference Include="FluentMigrator.Runner.MySql" Version="7.1.0" />
    <PackageReference Include="FluentMigrator.Runner.Postgres" Version="7.1.0" />
    <PackageReference Include="FluentMigrator.Runner.SQLite" Version="7.1.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="Npgsql" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.0" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="SwiftlyS2.CS2" Version="*-*" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="TimeSpanParserUtil" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="resources/gamedata/**/*;resources/templates/**/*;resources/translations/**/*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Remove="FluentMigrator.Runner.Db2" />
    <TrimmerRootAssembly Remove="FluentMigrator.Runner.Firebird" />
    <TrimmerRootAssembly Remove="FluentMigrator.Runner.Hana" />
    <TrimmerRootAssembly Remove="FluentMigrator.Runner.Oracle" />
    <TrimmerRootAssembly Remove="FluentMigrator.Runner.Redshift" />
    <TrimmerRootAssembly Remove="FluentMigrator.Runner.Snowflake" />
    <TrimmerRootAssembly Remove="FluentMigrator.Runner.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Admins.Bans.Contract/Admins.Bans.Contract.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Admins.Menu.Contract/Admins.Menu.Contract.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Admins.Core.Contract/Admins.Core.Contract.csproj" />
  </ItemGroup>

    <Target Name="CopyContractToExports" AfterTargets="Build">
		<Copy SourceFiles="$(MSBuildThisFileDirectory)../Admins.Bans.Contract/build/$(TargetFramework)/Admins.Bans.Contract.dll" DestinationFolder="$(MSBuildThisFileDirectory)resources/exports/" />
	</Target>

	<Target Name="CopyContractToExports" AfterTargets="Publish">
		<Copy SourceFiles="$(MSBuildThisFileDirectory)../Admins.Bans.Contract/build/$(TargetFramework)/Admins.Bans.Contract.dll" DestinationFolder="$(PublishDir)resources/exports/" />
	</Target>

  <Target Name="CreateZip" AfterTargets="Publish">
    <ItemGroup>
      <PublishFiles Include="$(PublishDir)**\*.*" />
    </ItemGroup>

    <ZipDirectory SourceDirectory="$(PublishDir)../" DestinationFile="$(OutputPath)../$(AssemblyName).zip" Overwrite="true" />
  </Target>

  <Target Name="RemoveRuntimeFolders" AfterTargets="Publish">
    <RemoveDir Directories="$(PublishDir)runtimes" />
  </Target>

  <Target Name="RemoveUnnecessaryDependencies" AfterTargets="Publish">
    <ItemGroup>
      <UnnecessaryDeps Include="$(PublishDir)FluentMigrator.Runner.Db2.dll" />
      <UnnecessaryDeps Include="$(PublishDir)FluentMigrator.Runner.Firebird.dll" />
      <UnnecessaryDeps Include="$(PublishDir)FluentMigrator.Runner.Hana.dll" />
      <UnnecessaryDeps Include="$(PublishDir)FluentMigrator.Runner.Oracle.dll" />
      <UnnecessaryDeps Include="$(PublishDir)FluentMigrator.Runner.Redshift.dll" />
      <UnnecessaryDeps Include="$(PublishDir)FluentMigrator.Runner.Snowflake.dll" />
      <UnnecessaryDeps Include="$(PublishDir)FluentMigrator.Runner.SqlServer.dll" />
      <UnnecessaryDeps Include="$(PublishDir)FluentMigrator.Extensions.SqlServer.dll" />
      <UnnecessaryDeps Include="$(PublishDir)FluentMigrator.Extensions.Oracle.dll" />
      <UnnecessaryDeps Include="$(PublishDir)FluentMigrator.Extensions.Snowflake.dll" />
      <UnnecessaryDeps Include="$(PublishDir)Azure.*.dll" />
      <UnnecessaryDeps Include="$(PublishDir)FirebirdSql.*.dll" />
      <UnnecessaryDeps Include="$(PublishDir)Microsoft.Data.SqlClient.dll" />
      <UnnecessaryDeps Include="$(PublishDir)Microsoft.SqlServer.*.dll" />
      <UnnecessaryDeps Include="$(PublishDir)Microsoft.Identity*.dll" />
    </ItemGroup>
    <Delete Files="@(UnnecessaryDeps)" />
  </Target>

</Project> 